use bacowine;

--APLICACION
CREATE TABLE vino (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(45) NOT NULL,
    clase VARCHAR(45) NOT NULL,
    tipo VARCHAR(45) NOT NULL, 
    graduacion DECIMAL(4,2) UNSIGNED NOT NULL CHECK (graduacion <= 100), 
    bodega VARCHAR(100) NOT NULL, 
    localidades VARCHAR(500) NOT NULL,
    foto LONGBLOB,
    activo BOOLEAN DEFAULT true NOT NULL
);

CREATE TABLE bodegas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(40) NOT NULL,
  anyoCreacion INT NOT NULL,
  localizGeo VARCHAR(40) NOT NULL,
  descripcion VARCHAR(500) NOT NULL,
  denominOrigen VARCHAR(40) NOT NULL,
  foto LONGBLOB,
  activo BOOLEAN DEFAULT true NOT NULL
);

CREATE TABLE usuario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user VARCHAR(40) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(10) NOT NULL
);

CREATE TABLE comentario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user VARCHAR(40) NOT NULL,
  idVino INT NOT NULL,
  texto VARCHAR(1000) NOT NULL,
  activo BOOLEAN DEFAULT true NOT NULL
);