version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql-data:/var/lib/mysql
      - ../mysql-init-files:/docker-entrypoint-initdb.d
  app:
    env_file: ./docker.env
    depends_on:
      - mysqldb
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    restart: unless-stopped
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
volumes: 
  mysql-data: