name: Google Compute Engine

on:
  push:
    paths-ignore:
      - ".github/**"
      - "*.md"
    branches:
      - main
      - develop
  workflow_dispatch:
jobs:  
  deployDev:
    name: Deploy to develop
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment:
      name: develop
      url: 'https://dev.bacowine.live'
    steps:
      - name: Rebuild docker
        uses: appleboy/ssh-action@master
        with:
          host: dev.bacowine.live
          username: dev
          key: ${{ secrets.GCP_PRIVATE_KEY }}
          port: 22
          script: cd /opt/BacoWine/ && sudo git pull && cd .docker && sudo docker-compose up --build -d

  deployProd:
    name: Deploy to production
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'https://bacowine.live'
    steps:
      - name: Rebuild docker
        uses: appleboy/ssh-action@master
        with:
          host: bacowine.live
          username: dev
          key: ${{ secrets.GCP_PRIVATE_KEY }}
          port: 22
          script: cd /opt/BacoWine/ && sudo git pull && cd .docker && sudo docker-compose up --build -d
