# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: 
  pull_request:
    branches: [main, develop]

jobs:
  tests:
    # Checkout the Repo
    runs-on: ubuntu-latest
    env:
      MYSQLDB_HOST: ${{ secrets.MYSQLDB_HOST }}
      MYSQLDB_USER: ${{ secrets.MYSQLDB_USER }}
      MYSQLDB_ROOT_PASSWORD: ${{ secrets.MYSQLDB_ROOT_PASSWORD }}
      MYSQLDB_DATABASE: ${{ secrets.MYSQLDB_DATABASE }}
      MYSQLDB_PORT: ${{ secrets.MYSQLDB_PORT }}
      NODE_PORT: ${{ secrets.NODE_PORT }}
    steps:
    - uses: actions/checkout@v2
    
    # Install Node 16
    - name: Use Node.js '16.x'
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    # Install dependencies
    - run: npm install
    
    # Run tests
    - run: npm test
